CREATE TABLE `t_failed_msg` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(50) DEFAULT NULL COMMENT '业务标识',
`OP_TYPE` varchar(50) DEFAULT NULL COMMENT '操作类型：INSERT,UPSERT,UPDATE,DELETE',
`RETRY_STATUS` char(1) NOT NULL DEFAULT '0' COMMENT '是否可重试：0-不可以 1-可以',
`MSG_CONTENT` json DEFAULT NULL COMMENT '消息内容：docData json',
`FAILED_REASON` varchar(2000) DEFAULT NULL COMMENT '失败原因',
`DATA_LOCK` varchar(50) DEFAULT NULL COMMENT '数据锁:机器IP',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`),
KEY `idx_tag` (`SERVICE_TAG`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=6117939 DEFAULT CHARSET=utf8 COMMENT='消息消费失败重试表';




CREATE TABLE `t_index` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(20) DEFAULT NULL COMMENT '业务标识',
`SHARDING_NUM` varchar(20) DEFAULT NULL COMMENT 'sharding个数',
`REPLICATION_NUM` varchar(20) DEFAULT NULL COMMENT '副本个数',
`MAPPING` json DEFAULT NULL COMMENT 'mapping结构',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8 COMMENT='index设置表';




CREATE TABLE `t_index_analyzer` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(20) DEFAULT NULL COMMENT '业务标识',
`NAME` varchar(50) DEFAULT NULL COMMENT '分析器名称',
`TOKENIZER` varchar(50) DEFAULT NULL COMMENT '分词器，支持ik,whitespace,standard',
`PINYIN_SEARCH` char(1) DEFAULT NULL COMMENT '是否支持拼音查询，1-支持，0-不支持',
`INTACT_DIC` varchar(200) DEFAULT NULL COMMENT '整词字典',
`SYNONYM_DIC` varchar(200) DEFAULT NULL COMMENT '同义词字典',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8 COMMENT='index分析器设置表';



CREATE TABLE `t_index_data_delete_trigger` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(20) DEFAULT NULL COMMENT '业务标识',
`DELETE_JSON` json DEFAULT NULL COMMENT '删除条件',
`TRIGGER_TYPE` char(1) DEFAULT NULL COMMENT '1-固定时间点触发， 2-周期触发',
`TRIGGER_TIME` varchar(50) DEFAULT NULL COMMENT '数字（单位分钟）/crontable 时间格式',
`LAST_TRIGGER_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上次触发时间',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8 COMMENT='索引数据自动删除定时器设置表';





CREATE TABLE `t_index_dictionary` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(20) DEFAULT NULL COMMENT '业务标识',
`TYPE` int(11) DEFAULT NULL COMMENT '1-整词字典，2-同义词字典，3-联想词字典',
`IS_LOCAL_FILE` char(1) DEFAULT NULL COMMENT '是否本地文件，1-是，0-远程服务器文件',
`DIC_PATH` varchar(200) DEFAULT NULL COMMENT '字典路径',
`DIC_NAME` varchar(200) DEFAULT NULL COMMENT '字典名称',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8 COMMENT='字典表';




CREATE TABLE `t_score_model` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(50) DEFAULT NULL COMMENT '业务标识',
`NAME` varchar(200) DEFAULT NULL COMMENT '模型名称',
`MODEL_TYPE` char(1) DEFAULT NULL COMMENT '1-手动开发的模型，2-机器学习模型',
`MODEL_CONTENT` varchar(2000) DEFAULT NULL COMMENT '模型内容',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COMMENT='二次排序模型';



CREATE TABLE `t_service_tag` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(20) DEFAULT NULL COMMENT '业务标识',
`ES_NAME` varchar(20) DEFAULT NULL COMMENT 'es集群名称',
`INDEX_ALIAS` varchar(20) DEFAULT NULL COMMENT '索引别名',
`TYPE_NAME` varchar(20) DEFAULT NULL COMMENT 'type名称',
`FULL_IMPORT_URL` varchar(100) DEFAULT NULL COMMENT '全量数据导入地址',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8 COMMENT='serviceTag配置表';





CREATE TABLE `t_service_tag_index` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(20) DEFAULT NULL COMMENT '业务标识',
`INDEX_NAME` varchar(100) DEFAULT NULL COMMENT 'index名称',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=356 DEFAULT CHARSET=utf8 COMMENT='index列表';





CREATE TABLE `t_service_tag_user` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(20) DEFAULT NULL COMMENT '业务标识',
`USER` varchar(20) DEFAULT NULL COMMENT '用户名',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=115 DEFAULT CHARSET=utf8 COMMENT='用户配置表';





CREATE TABLE `t_slow_method` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(20) DEFAULT NULL COMMENT '业务标识',
`TIME_MILLIS` int(11) DEFAULT NULL COMMENT '耗时(单位毫秒)',
`QUERY_PARAM` json DEFAULT NULL COMMENT '查询参数',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='slow method表';





CREATE TABLE `t_suggest_source_field` (
`ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`SERVICE_TAG` varchar(20) DEFAULT NULL COMMENT '业务标识',
`FILED_NAME` varchar(200) DEFAULT NULL COMMENT '字段名称',
`TYPE` int(11) DEFAULT NULL COMMENT '1-提示词字段，2-条件字段',
`LOGIC_DELETE` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0-未删除 1-已删除',
`UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COMMENT='联想词字典来源';